apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MONGODB_PASSWORD
              name: env-backend-env
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MONGODB_USERNAME
              name: env-backend-env
        image: backend
        imagePullPolicy: ""
        name: backend
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /app/logs
          name: logs
        - mountPath: /app
          name: backend-claim1
        - mountPath: /app/node_modules
          name: backend-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: backend-claim1
        persistentVolumeClaim:
          claimName: backend-claim1
      - name: backend-claim2
        persistentVolumeClaim:
          claimName: backend-claim2
status: {}
