apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml

namespace: upwind-labs

images:
- name: backend
  newName: leandromarinh/backend
  newTag: 549f3ff89582ddcea6a1a58bedd1714518deb9fa
- name: frontend
  newName: leandromarinh/frontend
  newTag: 549f3ff89582ddcea6a1a58bedd1714518deb9fa
