name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      frontend_sha: ${{ steps.get_frontend_sha.outputs.sha }}
      backend_sha: ${{ steps.get_backend_sha.outputs.sha }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build frontend image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          path: ./frontend
          username: leandromarinh
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: leandromarinh/frontend
          tags: ${{ github.sha }}, latest

      - name: get frontend sha
        id: get_frontend_sha
        run: echo "::set-output name=sha::$(docker inspect --format='{{index .RepoDigests 0}}' leandromarinh/frontend | cut -d'@' -f2)"

      - name: build backend image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          path: ./backend
          username: leandromarinh
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: leandromarinh/backend
          tags: ${{ github.sha }}, latest

      - name: get backend sha
        id: get_backend_sha
        run: echo "::set-output name=sha::$(docker inspect --format='{{index .RepoDigests 0}}' leandromarinh/backend | cut -d'@' -f2)"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Pull changes from main branch
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: 4.5.7

      - name: update kubernetes
        run: |
          cd kubernetes
          kustomize edit set image frontend=leandromarinh/frontend:${{ github.sha }} backend=leandromarinh/backend:${{ github.sha }}
          cat kustomization.yaml

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"

      - name: Commit changes
        run: |
          git add .
          git commit -m "image update done by kustomization"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  upwind:
    name: Upwind
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Integrate backend image
        env:
          IMAGE: leandromarinh/backend
          IMAGE_SHA: ${{ needs.build.outputs.backend_sha }}
          UPWIND_API_ENDPOINT: https://api.upwind.io
          UPWIND_AUTH_ENDPOINT: https://auth.upwind.io
          UPWIND_ORGANIZATION_ID: ${{ secrets.UPWIND_ORGANIZATION_ID }}
          UPWIND_CLIENT_SECRET: ${{ secrets.UPWIND_CLIENT_SECRET }}
          UPWIND_CLIENT_ID: ${{ secrets.UPWIND_CLIENT_ID }}
        run: |
          # Get Access Token
          response=$(curl -s --location "${UPWIND_AUTH_ENDPOINT}/oauth/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=${UPWIND_API_ENDPOINT}" \
            --data-urlencode "client_id=${UPWIND_CLIENT_ID}" \
            --data-urlencode "client_secret=${UPWIND_CLIENT_SECRET}")
          ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')

          # Call Upwind API
          CURL_CMD="curl -fsSL \"${UPWIND_API_ENDPOINT}/v1/organizations/$UPWIND_ORGANIZATION_ID/events\" \
            --request POST \
            --write-out \"\n%{http_code}\" \
            --header \"Content-Type: application/json\" \
            --header \"Authorization: Bearer $ACCESS_TOKEN\" \
            --data '{
                \"type\": \"image_build\",
                \"reporter\": \"github_actions\",
                \"data\" :{
                    \"image\" : \"${IMAGE}\",
                    \"commit_sha\" : \"${GITHUB_SHA}\",
                    \"repository\": \"https://github.com/${GITHUB_REPOSITORY}.git\",
                    \"branch\": \"${GITHUB_REF_NAME}\",
                    \"image_sha\": \"${IMAGE_SHA}\",
                    \"build_time\" : \"$(date +'%Y-%m-%dT%H:%M:%SZ')\"
                }
              }'
            "
            response=$(eval "${CURL_CMD}")
            echo "${response}"
            response_code=$(echo "${response}" | tail -n 1)
            response_body=$(echo "${response}" | sed '$ d' | jq '.')
            echo "Status Code: ${response_code}"
            echo "Response:"
            echo "${response_body}"
      - name: Integrate frontend image
        env:
          IMAGE: leandromarinh/frontend
          IMAGE_SHA: ${{ needs.build.outputs.frontend_sha }}
          UPWIND_API_ENDPOINT: https://api.upwind.io
          UPWIND_AUTH_ENDPOINT: https://auth.upwind.io
          UPWIND_ORGANIZATION_ID: ${{ secrets.UPWIND_ORGANIZATION_ID }}
          UPWIND_CLIENT_SECRET: ${{ secrets.UPWIND_CLIENT_SECRET }}
          UPWIND_CLIENT_ID: ${{ secrets.UPWIND_CLIENT_ID }}
        run: |
          # Get Access Token
          response=$(curl -s --location "${UPWIND_AUTH_ENDPOINT}/oauth/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=${UPWIND_API_ENDPOINT}" \
            --data-urlencode "client_id=${UPWIND_CLIENT_ID}" \
            --data-urlencode "client_secret=${UPWIND_CLIENT_SECRET}")
          ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')

            # Call Upwind API
          CURL_CMD="curl -fsSL \"${UPWIND_API_ENDPOINT}/v1/organizations/$UPWIND_ORGANIZATION_ID/events\" \
            --request POST \
            --write-out \"\n%{http_code}\" \
            --header \"Content-Type: application/json\" \
            --header \"Authorization: Bearer $ACCESS_TOKEN\" \
            --data '{
                \"type\": \"image_build\",
                \"reporter\": \"github_actions\",
                \"data\" :{
                    \"image\" : \"${IMAGE}\",
                    \"commit_sha\" : \"${GITHUB_SHA}\",
                    \"repository\": \"https://github.com/${GITHUB_REPOSITORY}.git\",
                    \"branch\": \"${GITHUB_REF_NAME}\",
                    \"image_sha\": \"${IMAGE_SHA}\",
                    \"build_time\" : \"$(date +'%Y-%m-%dT%H:%M:%SZ')\"
                }
              }'
            "
          response=$(eval "${CURL_CMD}")
          echo "${response}"
          response_code=$(echo "${response}" | tail -n 1)
          response_body=$(echo "${response}" | sed '$ d' | jq '.')
          echo "Status Code: ${response_code}"
          echo "Response:"
          echo "${response_body}"


# testando pull request